import type { LangKey, LangStrings } from "./content-types";

export const lang: Record<LangKey, LangStrings> = {
  en: {
    heroEyebrow: "Frontend Developer — AI Automation",
    heroRole1: "I don't just write code.",
    heroRole2: "I design digital experiences",
    heroRole3: "— and teach systems to run them.",
    availability: "OPEN TO SELECT PROJECTS AND CREATIVE COLLABORATIONS",
    viewWork: "VIEW MY WORK",
    startProject: "START A PROJECT",
    contact: "CONTACT",
    work: "WORK",
    services: "SERVICES",
    about: "ABOUT",
    caseStudy: "CASE STUDY",
    liveDemo: "LIVE DEMO",
    github: "GITHUB",
    demoOnRequest: "DEMO AVAILABLE ON REQUEST",
    nextProject: "Next Project",
    backToWork: "Back to Work",
    langToggle: "عربي",
    skipToContent: "Skip to content",
    close: "Close",
    scroll: "Scroll",
  },
  ar: {
    heroEyebrow: "مطور واجهات أمامية — أتمتة بالذكاء الاصطناعي",
    heroRole1: "أنا لا أكتب برمجيات فحسب.",
    heroRole2: "أصمم تجارب رقمية",
    heroRole3: "— وأُعلّم الأنظمة كيف تعمل.",
    availability: "متاح لمشاريع محددة وتعاونات إبداعية",
    viewWork: "شاهد أعمالي",
    startProject: "ابدأ مشروعًا",
    contact: "تواصل",
    work: "أعمالي",
    services: "الخدمات",
    about: "عني",
    caseStudy: "دراسة الحالة",
    liveDemo: "عرض مباشر",
    github: "جيتهب",
    demoOnRequest: "العرض متاح عند الطلب",
    nextProject: "المشروع التالي",
    backToWork: "العودة للأعمال",
    langToggle: "EN",
    skipToContent: "تخطى إلى المحتوى",
    close: "إغلاق",
    scroll: "مرر",
  },
};